
de {



notify('Started')



try {



// Get Artifactory server instance, defined in the Artifactory Plugin administration page.

    def server = Artifactory.server "01"

    def buildInfo = Artifactory.newBuildInfo() 



// Project Dir

    def project_path = "Download"





stage('GitCheckOut') {

git branch: 'stage', credentialsId: '01', url: 'https://github.com/jyothi-hs/Petclinic.git'

}







dir(project_path){



stage('Build Managment') {

      def downloadSpec = """{

	 "files": [

	{

	"pattern": "petclinic-war/*.war",

	"target": "files/"

        }

	]

	}"""

	server.download spec: downloadSpec

 }



stage('Deployment - Stage'){

  deploy adapters: [tomcat8(credentialsId: '02', path: '', url: 'http://jamhy83771dns.eastus2.cloudapp.azure.com:8080/')], contextPath: 'petclinic', onFailure: false, war: 'files/petclinic.war'
}
}



  notify('Completed')

} catch(err){

  notify("Error ${err}")

  currentBuild.result = 'FAILURE'

 }

}



def notify(status){

    emailext(

    to: "jyothikahsgowda@gmail.com",

    subject: "${status} :JOB '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",

    body:"""<p>${status}: :JOB '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>

            <p>Check Console output at <a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a></p>""",

    )

}
